"use strict";
exports.__esModule = true;
var LinkedList_1 = require("./LinkedList");
var linkedList = new LinkedList_1.LinkedList();
linkedList.insertFirstNode1(1);
linkedList.insertFirstNode1(2);
linkedList.insertFirstNode1(3);
linkedList.insertFirstNode1(30);
linkedList.insertLastNode(40);
console.log(linkedList.getSize());
console.log(linkedList.readList());
